### ISSUE TITLE
[Enhancement] - Create an icon for the website

### ISSUE THREAD

**Issue by VivekChatterjee** [VivekChatterjee/movie-reviewer#1]
Create an icon for the website matching its purpose

**Comment by uditagrawal08** [comment]
@VivekChatterjee  I want to work on this issue, may you assign this issue to me and please elaborate further

**Comment by VivekChatterjee** [comment]
@uditagrawal08 so the icon has to be related to movies
It should contain camera, reel, theater or anything which give movie vibes

**Comment by gautam-bhagat** [comment]
Hey assign this to me
