### ISSUE TITLE
Improved UI for movie search result

### ISSUE THREAD

**Issue by Ezzywealth** [VivekChatterjee/movie-reviewer#8]
I noticed that the UI for the movie search result display is distorted for desktop and mobile views.
The movie descriptions are not well placed and the UI needs improvements as well.
![Screenshot 2023-10-16 080857](https://github.com/VivekChatterjee/movie-reviewer/assets/86690432/cd14179d-4b2b-4695-9ca8-92205f6855bd)

**Comment by VivekChatterjee** [comment]
You can proceed @Ezzywealth
